### ISSUE TITLE
IN: Onboarding 

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-vampire#19]
After the onboarding routes for the backend and onboarding frontend is done, integrate

**Comment by singhmi4** [comment]
Might be useful for handling the onsubmit function to the back-end:
https://stackoverflow.com/questions/55738364/post-form-data-from-react-handle-submit-function-to-python-api
https://medium.com/better-programming/building-secure-login-flow-with-oauth-2-openid-in-react-apps-ce6e8e29630a
https://lepture.com/en/2013/create-oauth-server
https://github.com/lepture/flask-oauthlib/tree/master/tests/oauth2
https://github.com/authlib/example-oidc-server

**Comment by singhmi4** [comment]
The PR linked to this ticket takes care of the OAuth2 in the front-end as opposed to the back-end which was originally within this ticket: #14
