### ISSUE TITLE
BE: Database setup in Node.js

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-vampire#39]
mongo

This will also include: 
https://github.com/hatchways/team-vampire/issues/44

**Comment by singhmi4** [comment]
Ubuntu 18.04 MongoDB Install/Uninstall Guide:
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

Mongoose Docs:
https://mongoosejs.com/docs/index.html

Populating Database:
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

**Comment by singhmi4** [comment]
Database setup complete with mongoDB
