### ISSUE TITLE
Fix/Optimization: Adding New Event Type to Dashboard

### ISSUE THREAD

**Issue by singhmi4** [hatchways/team-vampire#61]
### Expected Behavior
* after hitting submit to create a New Event Type, it should show up on the user's dashboard right away

### Actual Behavior
* after hitting submit to create a New Event Type, you need to manually refresh the page to see the event type added to the dashboard

**Comment by singhmi4** [comment]
Hi @bonnieli , I'm trying to fix this issue by returning the meetingType object instead of the id when the user object is returned after successful authentication instead of doing another fetch GET request to the meetingType controller by passing in the userId.

The branch that I'm attempting to do this on is here:
https://github.com/hatchways/team-vampire/tree/feature-fix-render-new-event-type-dashboard

In ./server/utils/passport.js lines 23 - 42, I added the `populate` method to return the meetingType object instead of the id:
```js
let user = await User.findOne({ googleId: profile.id })
            .populate("availabilities", {
                day: 1,
                startTime: 1,
                endTime: 1
            })
            .populate({
                path: "meetingTypes",
                model: "MeetingType",
                populate: {
                    path: "appointments",
                    model: "Appointment",
                    select: {
                        "name": 1,
                        "email": 1,
                        "time": 1,
                        "timezone": 1
                    }
                }
            });
```
Since in ./server/controllers/auth.js is where the front-end makes the fetch request to the route "/users/me" which returns the signed in user along with other key-value pairs (lines 19 - 27):
```js
authRouter.get("/users/me", ensureAuth, (request, response) => {
    console.log(request.user);
    response.status(200).json({
        authenticated: true,
        message: "user successfully authenticated",
        user: request.user,
        cookies: request.cookies
    });
});
```

However, I'm still seeing the meetingTypes array in the `request.user` object returned as ids and not the objects which I expected to happen after using `populate` method.

Server Console.log below:
```js
Method: GET
Path:   /api/auth/users/me
Body:   {}
---
{ availabilities: [],
  meetingTypes:
   [ 5fc121586f9898142d703362,
     5fc121f16f9898142d703363,
     5fc17db56a6d9e07117b46b4,
     5fc2c6dd85d23607975d01da,
     5fc2df2f85d23607975d01db,
     5fc6a7cbb0709318ac291b26,
     5fc6a9cdb0709318ac291b27,
     5fc80ec2c7f51c0ad1d3c5ab,
     5fc80eecc7f51c0ad1d3c5ac,
     5fc81538c7f51c0ad1d3c5ad,
     5fc816fcc7f51c0ad1d3c5ae,
     5fc81727c7f51c0ad1d3c5af ],
  _id: 5fb8094f8c6825146949b002,
  googleId: '104348754318193001966',
  firstName: 'Michael',
  lastName: 'S',
  email: 'singh.michaelanthony@gmail.com',
  profilePicture:
   'https://lh3.googleusercontent.com/a-/AOh14GjAmMF8c19hWYlzl5fdYAyn5VS0iKNv95ugXtl_Pw=s96-c',
  createdAt: 2020-11-20T18:22:07.872Z,
  updatedAt: 2020-11-20T18:22:07.872Z,
  __v: 12 }
```

Not sure why the `populate` method isn't replacing the meetingType id's with the actual object information.

**Comment by singhmi4** [comment]
Hi @bonnieli  Figured out that the user object being returned is from the `passport.deserializeUser` method so I attached the `populate` method onto that and it worked!
```js
passport.deserializeUser((id, done) => {
        User.findById(id, (err, user) => done(err, user))
            .populate("availabilities", {
                day: 1,
                startTime: 1,
                endTime: 1
            })
            .populate({
                path: "meetingTypes",
                model: "MeetingType",
                populate: {
                    path: "appointments",
                    model: "Appointment",
                    select: {
                        "name": 1,
                        "email": 1,
                        "time": 1,
                        "timezone": 1
                    }
                }
            });
    });
```
The issue with the page component not updating unless I manually refresh is still not showing the newly added event Type. I'm thinking I'm needing to trigger the user state to re-render.

**Comment by bonnieli** [comment]
> The issue with the page component not updating unless I manually refresh is still not showing the newly added event Type. I'm thinking I'm needing to trigger the user state to re-render.

I'm thinking from looking at your branch so far, unless you have changed something but didn't push it yet is that you're not updating your `user` state with the new information, only console logging it https://github.com/hatchways/team-vampire/compare/feature-fix-render-new-event-type-dashboard#diff-87b1b0dee96ec6943c74dd34d728ceccf91aa3f1d5cbc646b997439095e535baR52

**Comment by singhmi4** [comment]
@bonnieli I think I understand what you mean. So if I pass `setUser` as one of the value props in my UserProvider context to be consumed by the NewEventType.js, I should do another get fetch request to retrieve the user object from the following controller:
```js
authRouter.get("/users/me", ensureAuth, (request, response) => {
    console.log(request.user);
    response.status(200).json({
        authenticated: true,
        message: "user successfully authenticated",
        user: request.user,
        cookies: request.cookies
    });
});
```
and `setUser` to the response I get back from it following the post request?

The flow will be like:
POST request to meetingType controller => /meeting_type
GET request to auth controller =>  /users/me => `setUser(response)`
